package com.rotarit.clujlive.controllers;

import org.springframework.web.bind.annotation.RestController;

import com.rotarit.clujlive.GooglePlacesClient;
import com.rotarit.clujlive.PlaceRepository;
import com.rotarit.clujlive.models.Place;

// import org.json.JSONObjects
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@RestController
@CrossOrigin
public class ClujliveController {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private PlaceRepository placeRepository;
    @Autowired
    private GooglePlacesClient google;

    @RequestMapping("/")
    @GetMapping
    public Iterable<Place> index() {
        return placeRepository.findAll();
    }

    @RequestMapping("/rating")
    @GetMapping
    public float placeRating(String placeID) {
        try {
            float temp = google.makeRatingRequest(placeID);
            System.out.println(temp);
            return 0;
        } catch (Exception e) {
            e.printStackTrace();
            return -1;
        }
    }
}
