package com.rotarit.clujlive.controllers;

import org.springframework.web.bind.annotation.RestController;

import com.rotarit.clujlive.PlaceRepository;
import com.rotarit.clujlive.models.Place;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@RestController
@CrossOrigin
public class ClujliveController {
    @Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PlaceRepository placeRepository;

    @RequestMapping("/")
    @GetMapping

    public Iterable <Place> index() {
        // Place[] place_holder = new Place[2];
        // place_holder[0] = new Place("TestPlace", 46.7695316f, 23.5966936f);
        // place_holder[1] = new Place("TestPlace2", 46.7605316f, 23.5966936f);
        return placeRepository.findAll();
    }
}