package com.rotarit.clujlive.controllers;

import org.springframework.web.bind.annotation.RestController;

import com.rotarit.clujlive.GooglePlacesClient;
import com.rotarit.clujlive.PlaceRepository;
import com.rotarit.clujlive.models.Place;

import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@RestController
@CrossOrigin
public class ClujliveController {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private PlaceRepository placeRepository;
    @Autowired
    private GooglePlacesClient google;

    @RequestMapping("/")
    @GetMapping
    public Iterable<Place> index() {
        return placeRepository.findAll();
    }

    @RequestMapping("/details")
    @GetMapping
    public ResponseEntity<?> placeRating(String placeID) {
        try {
            // JSONObject temp = google.makeDetailsRequest(placeID);
            // System.out.println(temp);
            // return new ResponseEntity<>(temp.toString(), HttpStatus.OK);
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}
